### PR TITLE
Breaking change of function interface

### LINKED ISSUE #13: Spec for ZenEx.Model.Ticket.Show does not include `nil` return type
Great library - enjoying it so far. 

I did find one tiny issue that's throwing me some Dialyzer warnings. The spec on [line 35](https://github.com/otoyo/zen_ex/blob/master/lib/zen_ex/core/models/ticket.ex#L35) for `ZenEx.Model.Ticket.Show` does not account for `nil`. I think that's because HTTPotion's spec for `get` doesn't include that possibility, either.

Unfortunately, it's possible to get a `nil` when the element doesn't exist on Zendesk:
```
iex(1)> ZenEx.Model.Ticket.show(-123)
nil
```

That also rings true for Locale and User:
```
iex(2)> ZenEx.Model.User.show(-123)
nil
iex(3)> ZenEx.Model.Locale.show(1231238129321381293912389)
nil
```

I can submit a quick PR that adds the `nil` return type for the specs and link it here if that works.

### LINKED ISSUE #27: Don't assume JSON response
### Context
According to the ZenDesk documentation (and my own real-life observations):
[**zendesk developers | Introduction | Requests**](https://developer.zendesk.com/api-reference/introduction/requests/)
> You may get a `text/plain` response in case of an error like a bad request. You should treat this as an error you need to fix.

### Problem
The current behavior:
```elixir
Mix.install([
  {:poison, "~> 3.1"},
  {:tesla, "~> 1.4.4"},
  {:zen_ex, "~> 0.7.0"}
])

import ZenEx.HTTPClient, only: [_build_entity: 2]
alias Tesla.Env
alias ZenEx.Entity.Ticket

decode_as = [ticket: Ticket]
status = 400
body = "<html><body>Error: Foo</body></html>"
response = %Env{body: body, status: status}

response |> _build_entity(decode_as)
```
which returns the exception:
```
** (Poison.SyntaxError) Unexpected token at position 0: <
    (poison 3.1.0) lib/poison/parser.ex:57: Poison.Parser.parse!/2
    (poison 3.1.0) lib/poison.ex:83: Poison.decode!/2
    (zen_ex 0.7.0) lib/zen_ex/http_client.ex:77: ZenEx.HTTPClient._build_entity/2
```

### Expected
In order to troubleshoot and fix the error, I want to know the HTTP status code and the raw response body in a `{:error, reason}` response, eg:
```elixir
{:error, "Unexpected response with HTTP status code 400 and body: \"<html><body>Error: Foo</body></html>\""}
```

### LINKED ISSUE #28: Don't ignore the HTTP status code
### Context
- [zendesk developers | Introduction | **Requests**](https://developer.zendesk.com/api-reference/introduction/requests)
  > ## [Status codes](https://developer.zendesk.com/api-reference/introduction/requests/#status-codes)
  > Responses may have the status codes described in the following sections.
  > #### [200 range](https://developer.zendesk.com/api-reference/introduction/requests/#200-range)
  > #### [400 range](https://developer.zendesk.com/api-reference/introduction/requests/#400-range)
  > #### [500 range](https://developer.zendesk.com/api-reference/introduction/requests/#500-range)
- [zendesk developers | Ticketing | MANAGING TICKETS | Creating and updating tickets | **Protecting against ticket update collisions**](https://developer.zendesk.com/documentation/ticketing/managing-tickets/creating-and-updating-tickets/#protecting-against-ticket-update-collisions)
  - describes a valid use case where the HTTP status code of [409](https://www.webfx.com/web-development/glossary/http-status-codes/what-is-a-409-status-code/) can be expected and should properly be handled.
  - This is also linked from the [API Reference | TICKETS | **Update Ticket**](https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#update-ticket)
- [zendesk developers | Introductions | **Rate limits | Monitoring your request activity**](https://developer.zendesk.com/api-reference/introduction/rate-limits/#monitoring-your-request-activity)
  > If the rate limit is exceeded, the API responds with a HTTP [429 Too Many Requests](http://tools.ietf.org/html/draft-nottingham-http-new-status-02#section-4) response code and a body that details the reason for the rate limiter kicking in. The response has a `Retry-After` header that tells you for how many seconds to wait before retrying.

### Problem
Current behavior:
```elixir
Mix.install([
  {:poison, "~> 3.1"},
  {:tesla, "~> 1.4.4"},
  {:zen_ex, "~> 0.7.0"}
])

import ZenEx.HTTPClient, only: [_build_entity: 2]
alias Tesla.Env
alias ZenEx.Entity.Ticket

decode_as = [ticket: Ticket]
status = 409
body = """
{
  "description": "Safe Update prevented the update due to outdated ticket data.
                   Please fetch the latest ticket data and try again.",
  "error": "UpdateConflict"
}
"""
response = %Env{body: body, status: status}
response |> _build_entity(decode_as)
# => nil
```
returns nothing

### Expected
In order to troubleshoot and properly handle non 200-range errors,  I want to know the HTTP status code and the raw response body

### PR DESCRIPTION
**Pull request by otoyo**
Fixed https://github.com/otoyo/zen_ex/issues/13, fixed https://github.com/otoyo/zen_ex/issues/27, fixed https://github.com/otoyo/zen_ex/issues/28

`ZenEx.HTTPClient` client now returns `{:ok, _}` or `{:error, _}`.

### CODE REVIEW

File: lib/zen_ex/core/models/ticket.ex [hunk 1]
```diff
@@ -14,10 +14,10 @@ defmodule ZenEx.Model.Ticket do
   ## Examples
 
       iex> ZenEx.Model.Ticket.list
-      %ZenEx.Collection{}
+      {:ok, %ZenEx.Collection{}}
 
   """
-  @spec list :: %ZenEx.Collection{} | {:error, String.t()}
+  @spec list :: {:ok, %ZenEx.Collection{}} | {:error, any()}
```
Comment (esambo) [inline lib/zen_ex/core/models/ticket.ex:20]: It would be nice to create [User-defined types](https://hexdocs.pm/elixir/1.12/typespecs.html#user-defined-types) and prevent [Credo.Check.Warning.SpecWithStruct](https://hexdocs.pm/credo/Credo.Check.Warning.SpecWithStruct.html)
